apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert --file ../docker-compose-k8s.yml
    kompose.version: 1.26.1 (a9d05d509)
  creationTimestamp: null
  labels:
    io.kompose.service: home-timeline-redis
  name: home-timeline-redis
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: home-timeline-redis
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert --file ../docker-compose-k8s.yml
        kompose.version: 1.26.1 (a9d05d509)
      creationTimestamp: null
      labels:
        io.kompose.service: home-timeline-redis
    spec:
      containers:
        - args:
            - /social-network-microservices/config/redis.conf
          image: localhost:5000/redis:6.2.4
          name: home-timeline-redis
          ports:
            - containerPort: 6379
          resources: {}
      hostname: home-timeline-redis
      restartPolicy: Always
status: {}
