apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert --file ../docker-compose-k8s.yml
    kompose.version: 1.26.1 (a9d05d509)
  creationTimestamp: null
  labels:
    io.kompose.service: media-service
  name: media-service
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: media-service
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert --file ../docker-compose-k8s.yml
        kompose.version: 1.26.1 (a9d05d509)
      creationTimestamp: null
      labels:
        io.kompose.service: media-service
    spec:
      containers:
        - command:
            - MediaService
          image: localhost:5000/social-network-ml-microservices:latest
          name: media-service
          ports:
            - containerPort: 9090
          resources: {}
      hostname: media-service
      restartPolicy: Always
status: {}
