apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert --file ../docker-compose-k8s.yml
    kompose.version: 1.26.1 (a9d05d509)
  creationTimestamp: null
  labels:
    io.kompose.service: nginx-thrift
  name: nginx-thrift
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: nginx-thrift
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert --file ../docker-compose-k8s.yml
        kompose.version: 1.26.1 (a9d05d509)
      creationTimestamp: null
      labels:
        io.kompose.service: nginx-thrift
    spec:
      containers:
        - image: localhost:5000/openresty-thrift-ml:xenial
          name: nginx-thrift
          ports:
            - containerPort: 8080
          resources: {}
      hostname: nginx-thrift
      restartPolicy: Always
status: {}
