apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert --file ../docker-compose-k8s.yml
    kompose.version: 1.26.1 (a9d05d509)
  creationTimestamp: null
  labels:
    io.kompose.service: post-storage-memcached
  name: post-storage-memcached
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: post-storage-memcached
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert --file ../docker-compose-k8s.yml
        kompose.version: 1.26.1 (a9d05d509)
      creationTimestamp: null
      labels:
        io.kompose.service: post-storage-memcached
    spec:
      containers:
        - image: localhost:5000/memcached:1.6.7
          name: post-storage-memcached
          ports:
            - containerPort: 11211
          resources: {}
      hostname: post-storage-memcached
      restartPolicy: Always
status: {}
