apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert --file ../docker-compose-k8s.yml
    kompose.version: 1.26.1 (a9d05d509)
  creationTimestamp: null
  labels:
    io.kompose.service: url-shorten-mongodb
  name: url-shorten-mongodb
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: url-shorten-mongodb
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert --file ../docker-compose-k8s.yml
        kompose.version: 1.26.1 (a9d05d509)
      creationTimestamp: null
      labels:
        io.kompose.service: url-shorten-mongodb
    spec:
      containers:
        - args:
            - --config
            - /social-network-microservices/config/mongod.conf
          image: localhost:5000/mongo:4.4.6
          name: url-shorten-mongodb
          ports:
            - containerPort: 27017
          resources: {}
      hostname: url-shorten-mongodb
      restartPolicy: Always
status: {}
