apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert --file ../docker-compose-k8s.yml
    kompose.version: 1.26.1 (a9d05d509)
  creationTimestamp: null
  labels:
    io.kompose.service: user-memcached
  name: user-memcached
spec:
  ports:
    - name: "11211"
      port: 11211
      targetPort: 11211
  selector:
    io.kompose.service: user-memcached
status:
  loadBalancer: {}
