#FROM ubuntu:16.04
#
#RUN apt-get update \
#  && apt-get install -y \
#    python3 \
#    python3-pip \
#  && pip3 install thrift

FROM python:3

ENV http_proxy=""
ENV https_proxy=""
ENV no_proxy=""

RUN pip install thrift
