apiVersion: apps/v1
kind: Deployment
metadata:
  name: locust-master
  labels:
    name: locust
    role: master
spec:
  selector:
    matchLabels:
      name: locust
      role: master
  replicas: 1
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        name: locust
        role: master
    spec:
      securityContext: {}
      containers:
      - name: locust-master
        securityContext: {}
        image: "localhost:5000/locust-ml:latest"
        command: ["/bin/bash", "/docker-entrypoint.sh"]
        # args: ["--config=/mnt/locust/configs/master.conf"]
        imagePullPolicy: Always
        resources: {}
        ports:
          - containerPort: 8089
            name: loc-master-web
            protocol: TCP
          - containerPort: 5557
            name: loc-master-p1
            protocol: TCP
          - containerPort: 5558
            name: loc-master-p2
            protocol: TCP
      restartPolicy: Always
